version: '3.8'

services:
  contro-bot:
    build: .
    container_name: contro-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"  # API port
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 